1650984206349	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1650989862503	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1650989862503	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1650989862506	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1650989862507	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1650989862541	Sync.SyncScheduler	DEBUG	Woke from sleep.
1650989862541	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1650989862541	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1650989862542	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1650989863087	Sync.Service	DEBUG	User-Agent: Firefox/99.0.1 (Linux x86_64) FxSync/1.101.0.20220413030647.desktop
1650989863087	Sync.Service	INFO	Starting sync at 2022-04-26 21:47:43 in browser session O_aMM1OIq9pR
1650989863087	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1650989863089	Sync.Status	INFO	Resetting Status.
1650989863089	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1650989863090	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1650989863090	FirefoxAccounts	DEBUG	getOAuthToken enter
1650989863090	FirefoxAccounts	TRACE	getCachedToken returning cached token
1650989863090	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1650989863090	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1650989863091	Sync.SyncAuthManager	INFO	Getting sync key
1650989863091	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1650989863091	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1650989863091	FirefoxAccounts	DEBUG	getOAuthToken enter
1650989863091	FirefoxAccounts	TRACE	getCachedToken returning cached token
1650989863091	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1650989863091	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1650989863092	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1650989863093	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1650989863093	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1650989863094	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1650989863094	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1650989863094	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1650989863094	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1650989863095	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1650989863096	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1650989863098	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1650989863098	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1650989863098	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1650989863098	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1650989863099	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1650989863099	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1650989863103	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
