1651075225139	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1651075225440	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1651089004487	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1651089004488	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1651089004491	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1651089004494	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1651089004571	Sync.SyncScheduler	DEBUG	Woke from sleep.
1651089004571	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1651089004571	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1651089004573	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1651089006572	Sync.Service	DEBUG	User-Agent: Firefox/99.0.1 (Linux x86_64) FxSync/1.101.0.20220413030647.desktop
1651089006572	Sync.Service	INFO	Starting sync at 2022-04-28 01:20:06 in browser session 5YI_j94807ex
1651089006572	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1651089006575	Sync.Status	INFO	Resetting Status.
1651089006575	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1651089006576	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1651089006576	FirefoxAccounts	DEBUG	getOAuthToken enter
1651089006576	FirefoxAccounts	TRACE	getCachedToken returning cached token
1651089006576	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1651089006577	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1651089006578	Sync.SyncAuthManager	INFO	Getting sync key
1651089006578	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1651089006578	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1651089006578	FirefoxAccounts	DEBUG	getOAuthToken enter
1651089006578	FirefoxAccounts	TRACE	getCachedToken returning cached token
1651089006578	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1651089006578	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1651089006579	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1651089006580	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1651089006581	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1651089006582	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1651089006582	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1651089006582	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1651089006582	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1651089006583	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1651089006584	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1651089007624	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1651089007625	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1651089007625	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1651089007625	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
1651089007625	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1651089007626	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1651089007629	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection was established, but no data was ever received"  nsresult: "0x804b0014 (NS_ERROR_NET_RESET)"  location: "<unknown>"  data: no] No traceback available
