1649932837539	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649937305480	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1649937305480	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649937305484	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1649937305485	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649937305524	Sync.SyncScheduler	DEBUG	Woke from sleep.
1649937305524	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1649937305524	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1649937305525	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1649937307525	Sync.Service	DEBUG	User-Agent: Firefox/99.0.1 (Linux x86_64) FxSync/1.101.0.20220413030647.desktop
1649937307525	Sync.Service	INFO	Starting sync at 2022-04-14 17:25:07 in browser session 35F-zgopUO2u
1649937307526	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1649937307528	Sync.Status	INFO	Resetting Status.
1649937307528	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1649937307528	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1649937307528	FirefoxAccounts	DEBUG	getOAuthToken enter
1649937307528	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649937307528	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649937307529	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1649937307529	Sync.SyncAuthManager	INFO	Getting sync key
1649937307530	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1649937307530	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1649937307530	FirefoxAccounts	DEBUG	getOAuthToken enter
1649937307530	FirefoxAccounts	TRACE	getCachedToken returning cached token
1649937307530	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1649937307530	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1649937307530	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1649937307532	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1649937307532	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1649937307533	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1649937307533	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649937307533	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1649937307533	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1649937307534	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.js:39:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.js:62:16
_tokenServerExchangeRequest@tokenserverclient.js:241:13
1649937307535	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1649937307536	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/194602547/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1649937307537	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1649937307537	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1649937307537	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1649937307537	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1649937307538	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1649937307544	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
